### PR TITLE
Add '--force-update'

### PR DESCRIPTION
**Pull request by thecakeisfalse**
@enty8080

### CODE REVIEW

**Comment by enty8080** [comment]
Why have you added `import socket`?

**Comment by thecakeisfalse** [comment]
in file ```hatsploit/utils/telnet.py```

https://github.com/EntySec/HatSploit/blob/main/hatsploit/utils/telnet.py#L118

unknown variable ```socket```

**Comment by enty8080** [comment]
Ok.

**Comment by enty8080** [comment]
I am not merging it. It's useless because of `--force-update`.

**Comment by thecakeisfalse** [comment]
@enty8080 why do you think that ```--force-update``` is useless?

**Comment by enty8080** [comment]
https://github.com/EntySec/HatSploit/pull/63#issuecomment-912995534

**Comment by enty8080** [comment]
BTW I am not merging PRs from people who talk like this.

**Comment by thecakeisfalse** [comment]
bruh

**Comment by thecakeisfalse** [comment]
@enty8080 why can't you just add this function by yourself?

**Pull request closed without merging**
