### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by thecakeisfalse**
@enty8080

### CODE REVIEW

**Comment by enty8080** [comment]
@thecakeisfalse `check_update` update is useless

**Comment by thecakeisfalse** [comment]
@enty8080 no
i updated ```check_update``` because i couldn't start hsf without internet

**Comment by enty8080** [comment]
@thecakeisfalse I fixed this already.

**Comment by thecakeisfalse** [comment]
@enty8080 ggwp ducking idiot

**Comment by enty8080** [comment]
@thecakeisfalse watch your speech, sir.

**Comment by thecakeisfalse** [comment]
@enty8080 lick the potato, sir

**Comment by enty8080** [comment]
@thecakeisfalse Sir,

**1.** Your issues do not contain any information about the problem. You do not want to fill any forms. I'll remove every issue if it does not contain these forms.

**2.** Your speech is bad and I'll report your abusive messages and answers. Watch your speech, no one will answer you if you'll continue talking like this.

**3.** Your contributions are useless.

**Comment by thecakeisfalse** [comment]
@enty8080 remove your ducking projects idiot

**Pull request closed without merging**
