### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by thecakeisfalse**
fix bugs in ```post/macos/shell/suspend```, ```post/unix/shell/getpid```, ```post/windows/misc/message_box```

```bash
[-] An error occurred in module: 'NoneType' object has no attribute 'send_command'!
```

### CODE REVIEW

**Comment by enty8080** [comment]
@thecakeisfalse That's fine, but you need to remove `self.print_error("Invalid session ID")` and change `if session is not None` to just `if session`.

**Comment by thecakeisfalse** [comment]
@enty8080 I think that users should know if they are trying to «attack» session with invalid id

**Comment by enty8080** [comment]
@thecakeisfalse Yes, I already did it here - https://github.com/EntySec/HatSploit/blob/f023ccfb37bfc5667508e4a429f9fab91aa21347/hatsploit/lib/modules.py#L200

**Comment by thecakeisfalse** [comment]
@enty8080
it don't show me any messages about session

```bash
(hsf)> use post/windows/misc/message_box
(hsf: post: Windows Invoke Message Box)> run
(hsf: post: Windows Invoke Message Box)> show options

Module Options (post/windows/misc/message_box):

    Option     Value             Required    Description           
    ------     -----             --------    -----------           
    MESSAGE    Hello, Friend!    yes         Message to show.      
    SESSION    0                 yes         Session to run on.    

(hsf: post: Windows Invoke Message Box)> 
```

**Comment by enty8080** [comment]
@thecakeisfalse Hmmmmmmmmmmmmmm*1024, maybe you should type `run`?

**Comment by thecakeisfalse** [comment]
@enty8080 lol
the second line of output contains ```run```

**Comment by enty8080** [comment]
@thecakeisfalse Ok, I'll take a look

**Comment by thecakeisfalse** [comment]
@enty8080 and you also have bug #60

**Comment by thecakeisfalse** [comment]
@enty8080 if I understand your code right, function ```compare_types``` works only when you use ```set``` in hsf. it doesn't work when you use ```run```

**Comment by enty8080** [comment]
@thecakeisfalse Of course I know this, I wrote code, lol :)

**Comment by enty8080** [comment]
@thecakeisfalse Bug fixed, next time fill in the bug report form:

issues -> bug report

**Pull request closed without merging**
